export const photos = [
    {
      name: "Electrolux",
      src: "./img/projects/project_gallery_1.png",
      title: "projects.electrolux.title",
      text: "projects.electrolux.banner_description",
      url: "Project?name=electrolux",
      alt: "Electrolux alt",
      buttonImg: "/img/usedStacks/Electrolux.png",
    },
    {
      name: "link_leito",
      src: "./img/projects/project_gallery_2.png",
      title: "projects.link_leito.title",
      text: "projects.link_leito.banner_description",
      url: "Project?name=link-leito",
      alt: "Link Leito alt",
      buttonImg: "/img/usedStacks/link_leito.png",
    },
    {
      name: "Tripper",
      src: "./img/projects/project_gallery_3.png",
      title: "projects.triper.title",
      text: "projects.triper.banner_description",
      url: "Project?name=triper",
      alt: "triper alt",
      buttonImg: "/img/usedStacks/Tripper.png",
    },
    {
      name: "comunity_alert",
      src: "./img/projects/project_gallery_4.png",
      title: "projects.comunity_alert.title",
      text: "projects.comunity_alert.banner_description",
      url: "Project?name=comunity-alert",
      alt: "comunity_alert alt",
      buttonImg: "",
    },
    {
      name: "match_coder",
      src: "./img/projects/project_gallery_5.png",
      title: "projects.match_coder.title",
      text: "projects.match_coder.banner_description",
      url: "Project?name=match-coder",
      alt: "match_coder alt",
      buttonImg: "",
    },
    {
      name: "pet_care",
      src: "./img/projects/project_gallery_6.png",
      title: "projects.pet_care.title",
      text: "projects.pet_care.banner_description",
      url: "Project?name=pet-care",
      alt: "pet_care alt",
      buttonImg: "",
    },
    {
      name: "the_chat",
      src: "./img/projects/project_gallery_7.png",
      title: "projects.the_chat.title",
      text: "projects.the_chat.banner_description",
      url: "Project?name=the-chat",
      alt: "the_chat alt",
      buttonImg: "/img/usedStacks/the_chat.png",
    },
    {
      name: "quest_game",
      src: "./img/projects/project_gallery_8.png",
      title: "projects.quest_game.title",
      text: "projects.quest_game.banner_description",
      url: "Project?name=quest-game",
      alt: "quest_game alt",
      buttonImg: "/img/usedStacks/quest_game.png",
    },
    {
      name: "blue_token",
      src: "./img/projects/project_gallery_9.png",
      title: "projects.blue_token.title",
      text: "projects.blue_token.banner_description",
      url: "Project?name=blue-token",
      alt: "blue_token alt",
      buttonImg: "/img/usedStacks/blue_token.png",
    },
    {
      name: "toro_token",
      src: "./img/projects/project_gallery_10.png",
      title: "projects.toro_token.title",
      text: "projects.toro_token.banner_description",
      url: "Project?name=toro-token",
      alt: "toro_token alt",
      buttonImg: "/img/usedStacks/toro_token.png",
    },
    {
      name: "genesis_bank",
      src: "./img/projects/project_gallery_11.png",
      title: "projects.genesis_bank.title",
      text: "projects.genesis_bank.banner_description",
      url: "Project?name=genesis-bank",
      alt: "genesis_bank alt",
      buttonImg: "/img/usedStacks/genesis_bank.png",
    },
    {
      name: "pet_system",
      src: "./img/projects/project_gallery_12.png",
      title: "projects.pet_system.title",
      text: "projects.pet_system.banner_description",
      url: "Project?name=pet-system",
      alt: "pet_system alt",
      buttonImg: "/img/usedStacks/pet_system.png",
    },

  ];
  